backend_project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/roles', function () {
////    $permission = Permission::create(['name' => 'view']);
////    $user = \App\User::find(2);
////      $user->assignRole('student');
////    dd($users);
////    $role = Role::find(2);
////    $permission = Permission::find(2);
////    $role->givePermissionTo($permission);
//});

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');
Auth::routes();
Route::get('/logout','AuthController@logout')
    ->name('logout');
Route::get('lang/{lang}','LangController@changeLang')->name('language');



Route::middleware('auth')->group(function(){

    // Chỉ có role là admin mới có thể truy cập vào các route của group này
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/','DashboardController@dashboard')
            ->name('home');
        Route::get('/dashboard','DashboardController@dashboard')
            ->name('dash');
        Route::match(['get','post'],'/register','AuthController@register')
            ->name('register');
        //student
        Route::resource('students', 'StudentController');
        //Course
        Route::resource('courses', 'CourseController');
        //Subject
        Route::resource('subjects', 'SubjectController');
        //Result
        Route::resource('results','ResultController');
        //SendMail
        Route::resource('email','SendMailController');
        Route::get( '/students/{id}/subject', 'StudentController@subject')->where(['[0-9]+'])
            ->name('students.subject');
        Route::put( '/students', 'StudentController@index')
            ->name('students.filter');
        Route::get( '/account/faker', 'StudentController@dataFaker');

        Route::group(['prefix' => 'chat'],function () {
            Route::get('/admin','ChatController@admin')->name('chat.admin');
        });

    });


        Route::post('/chat/pusher','ChatController@pusher')->name('chat.pusher');
        Route::get('/chat','ChatController@index')->name('chat.index');

        Route::get('/students/{student}','StudentController@show')->name('students.show');
        Route::get('/subjects-result','ResultController@index')->name('results.index');
        Route::put('/subjects-update','ResultController@updateForStudent')
            ->name('results.updateForStudent');


});

backend_project/resources/views/courses/add.blade.php
@extends('layouts.index')
@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Courses Add</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('courses.index') }}">Courses List</a></li>
            <li class="breadcrumb-item active">Courses Add</li>
        </ol>
        <div class="card">
            <div class="card-header">
                <i class="fab fa-wpforms"></i>
                Form Add Courses
            </div>
            <div class="card-body">
                <form action="{{ route('courses.store') }}" method="post">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputNam4">Name</label>
                            <input type="text" name="name" class="form-control" id="inputName4" placeholder="Name">
                            @error('name')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

backend_project/resources/views/courses/list.blade.php
@extends('layouts.index')
@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            {!! Session::get('success') !!}
        </div>
    @endif
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Courses List</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Courses List</li>
            </ol>
            <div class="card mb-4">
                <div class="nav-item col-md-2">
                    <a href="{{ route('courses.create') }}" class="btn btn-info">Add Courses</a>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    DataTable Courses
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead id="table" data-url="/courses" >
                            <tr>
                                <th>STT</th>
                                <th>Name</th>
                                <th>Option</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>Name</th>
                                <th width="200">Option</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            @foreach($courses as $index => $course)
                                <tr id="row-{{ $course->id }}">
                                    <td>{{$index+1}}</td>
                                    <td class="name-{{$course->id}}">{{ $course->name }}
                                        <a href="#"
                                            class="float-right btnUpdate"
                                            data-id="{{$course->id}}"
                                            data-value="{{$course->name}}"
                                            data-toggle="modal"
                                            data-target="#exampleModal">
                                            Rename
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{route('subjects.show', $course)}}" class="btn btn-info">Subjects</a>
                                        <button onclick="remove({{ $course->id }})" class="btn btn-danger">X</button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Update Courses</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <input type="text" name="name" class="form-control" id="inputUpdateName">
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary" id="update">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End modal -->
                </div>
            </div>
        </div>
    </main>
@endsection

backend_project/resources/views/courses/update.blade.php
@extends('layouts.index')
@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Courses Update</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('courses.list') }}">Courses List</a></li>
            <li class="breadcrumb-item active">Courses Update</li>
        </ol>
        <div class="card">
            <div class="card-header">
                <i class="fab fa-wpforms"></i>
                Form Update Courses
            </div>
            <div class="card-body">
                <form action="" method="post">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputNam4">Name</label>
                            <input type="text" name="name" class="form-control" id="inputName4" placeholder="Name">
                            @error('name')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection