backend_project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/roles', function () {
////    $permission = Permission::create(['name' => 'view']);
////    $user = \App\User::find(2);
////      $user->assignRole('student');
////    dd($users);
////    $role = Role::find(2);
////    $permission = Permission::find(2);
////    $role->givePermissionTo($permission);
//});

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');
Auth::routes();
Route::get('/logout','AuthController@logout')
    ->name('logout');
Route::get('lang/{lang}','LangController@changeLang')->name('language');



Route::middleware('auth')->group(function(){

    // Chỉ có role là admin mới có thể truy cập vào các route của group này
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/','DashboardController@dashboard')
            ->name('home');
        Route::get('/dashboard','DashboardController@dashboard')
            ->name('dash');
        Route::match(['get','post'],'/register','AuthController@register')
            ->name('register');
        //student
        Route::resource('students', 'StudentController');
        //Course
        Route::resource('courses', 'CourseController');
        //Subject
        Route::resource('subjects', 'SubjectController');
        //Result
        Route::resource('results','ResultController');
        //SendMail
        Route::resource('email','SendMailController');
        Route::get( '/students/{id}/subject', 'StudentController@subject')->where(['[0-9]+'])
            ->name('students.subject');
        Route::put( '/students', 'StudentController@index')
            ->name('students.filter');
        Route::get( '/account/faker', 'StudentController@dataFaker');

        Route::group(['prefix' => 'chat'],function () {
            Route::get('/admin','ChatController@admin')->name('chat.admin');
        });

    });


        Route::post('/chat/pusher','ChatController@pusher')->name('chat.pusher');
        Route::get('/chat','ChatController@index')->name('chat.index');

        Route::get('/students/{student}','StudentController@show')->name('students.show');
        Route::get('/subjects-result','ResultController@index')->name('results.index');
        Route::put('/subjects-update','ResultController@updateForStudent')
            ->name('results.updateForStudent');


});

backend_project/app/Models/Student.php
<?php

namespace App\Models;

use http\Env\Response;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = "students";

    protected $fillable = [
        'id','user_id','course_id','name','birthday','address','avatar','gender','phone','email','avg_score','status'
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }


    public function subjects()
    {
        $result = $this->hasMany(Subject::class,'course_id','course_id');
        if ($result) {
            return $result;
        }
        return false;
    }

    public function results()
    {
        $result = $this->belongsToMany(Subject::class, 'results')
            ->withPivot('id','score')
            ->withTimestamps();
        if ($result) {
            return $result;
        }
        return false;
    }


}

backend_project/app/Http/Controllers/Api/StudentController.php
<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Results\ResultCreateRequest;
use App\Http\Requests\Students\StudentCreateRequest;
use App\Http\Requests\Students\StudentUpdateRequest;
use App\Repositories\Courses\CourseRepository;
use App\Repositories\Results\ResultRepository;
use App\Repositories\Students\StudentRepository;
use App\Repositories\Subjects\SubjectRepository;
use App\Repositories\Users\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class StudentController extends Controller{
    protected $studentRepository;
    protected $courseRepository;
    protected $userRepository;
    protected $subjectRepository;
    protected $resultRepository;

    public function __construct(UserRepository $user, StudentRepository $student, CourseRepository $course, SubjectRepository $subject, ResultRepository $result)
    {
        $this->userRepository = $user;
        $this->studentRepository = $student;
        $this->courseRepository = $course;
        $this->subjectRepository = $subject;
        $this->resultRepository = $result;
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        //check file
        if ($request->hasFile('avatar'))
        {
            $data['avatar'] = $this->studentRepository->uploaderImage('update', $request);
        }
        //update user
        $this->userRepository->update($data['user_id'], $data);
        //update student
        $this->studentRepository->update($id, $data);
        //return
        return response()->json('Ok',200);
    }

    /**
     * @param $id
     * @return string
     */
    public function destroy($id)
    {
        $student = $this->studentRepository->find($id);
        $this->studentRepository->delete($id);
        $this->userRepository->delete($student->user_id);
        $this->resultRepository->deleteOnStudent($id);
        if ($student['avatar'] != 'null.png') {
            File::delete('./images/avatars/'.$student->avatar);
        }
        return "OK";
    }
}

backend_project/app/Http/Controllers/StudentController.php
<?php
namespace App\Http\Controllers;

use App\Http\Requests\Students\StudentCreateRequest;
use App\Http\Requests\Students\StudentFilterRequest;
use App\Http\Requests\Students\StudentUpdateRequest;
use App\Repositories\Courses\CourseRepository;
use App\Repositories\Results\ResultRepository;
use App\Repositories\Students\StudentRepository;
use App\Repositories\Subjects\SubjectRepository;
use App\Repositories\Users\UserRepository;
use Illuminate\Http\Request;

use Faker\Generator as Faker;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller{
    protected $studentRepository;
    protected $courseRepository;
    protected $userRepository;
    protected $subjectRepository;
    protected $resultRepository;

    public function __construct(UserRepository $user, StudentRepository $student, CourseRepository $course, SubjectRepository $subject, ResultRepository $result)
    {
        $this->userRepository = $user;
        $this->studentRepository = $student;
        $this->courseRepository = $course;
        $this->subjectRepository = $subject;
        $this->resultRepository = $result;
    }

    /**
     * Get students
     */
    public function index(StudentFilterRequest $request)
    {
        $students = $this->studentRepository->filter($request->all());
        return view("students.list", compact('students'), compact('request'));
    }


    /**
     * view create student
     */
    public function create()
    {
        $courses = $this->courseRepository->getAll();
        return view('students.add', compact('courses'));
    }

    /**
     * @param StudentCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StudentCreateRequest $request)
    {
        $data = $request->all();
        if ($request->hasFile('avatar')) {
            $data['avatar'] = $this->studentRepository->uploaderImage('create', $request);
        }
        //add user , get id user
        $data['user_id'] = $this->userRepository->create($data)->id;
        //add student
        $this->studentRepository->create($data);
        return redirect()->route('students.index')->with('success', 'Add Success Student');
    }

    /**
     * @param $id
     */
    public function edit($id){
        $result['courses'] = $this->courseRepository->getAll();
        $result['student'] = $this->studentRepository->find($id);
        return view('students.update', $result);
    }

    public function show($request)
    {
        $student = $this->studentRepository->getProfile(Auth::user());
        return view('students.info', compact('student'));
    }

    /**
     * update student
     * */
    public function update(StudentUpdateRequest $request, $id)
    {
        $data = $request->all();
        //check file
        if ($request->hasFile('avatar'))
        {
            $data['avatar'] = $this->studentRepository->uploaderImage('update', $request);
        }
        //update user
        $this->userRepository->update($data['user_id'], $data);
        //update student
        $this->studentRepository->update($id, $data);
        //return
        return redirect()->route('students.index')->with('success', 'Update Success Student');
    }

    /**
     * @param $id
     */
    public function subject($id)
    {
        $student = $this->studentRepository->find($id);
        if (!$student->course) {
            return redirect()->route('students.edit',$student)->with('error', 'Ngành học của sinh viên không tồn tại.');
        }
        $results = $student->results;
        $subjects =  $student->subjects->diff($results);
        return view('students.subject', compact('student','subjects','results'));
    }

    public function dataFaker(Faker $faker)
    {
        $limit = 500;
        for ($i=0; $i<$limit; $i++)
        {
            $data = [
                'name' => $faker->name,
                'birthday' =>$faker->date('Y-m-d','now'),
                'phone' => '0'.random_int(300000000,999999999),
                'email' => $faker->unique()->email,
                'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm',
                'gender' => random_int(0,1),
                'course_id' => 1,
                'address' => $faker->address,
                'avg_score' => 0

            ];
            $data['avatar'] = 'null.png';
            //add user , get id user
            $data['user_id'] = $this->userRepository->insertGetId($data);
            //add student
            $this->studentRepository->create($data);
        }
        return redirect()->route('students.index');

    }

}

backend_project/resources/views/students/add.blade.php
@extends('layouts/index')
@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Student Add</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ route('students.index') }}">Students List</a></li>
            <li class="breadcrumb-item active">Students Adđ</li>
        </ol>
        <div class="card">
            <div class="card-header btn">
                <i class="fab fa-wpforms"></i>
                Form Add Student
            </div>
            <div class="card-body">
                {{Form::open(array('url'=>route('students.store'),'method'=>'post', 'files'=>true))}}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputNam4">Name</label>
                            {{ Form::text('name',null,['class'=>'form-control','placeholder'=>'Name']) }}
{{--                            <input type="text" name="name" class="form-control" id="inputName4" placeholder="Name">--}}
                            @error('name')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputBirthday4">Birthday</label>
                            {{ Form::date('birthday',null,['class'=>'form-control','id'=>'example-date-input']) }}
{{--                            <input class="form-control" name="birthday" type="date" id="example-date-input">--}}
                            @error('birthday')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-md-2">
                            <label for="inputBirthday4">Gender</label>
                            {{ Form::select('gender', ['0' => 'Male','1' => 'Female'],null, ['class' => 'form-control', 'id'=>'inputState']) }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputemail2">Email</label>
                            {{ Form::email('email',null,['class'=>'form-control','placeholder'=>'example@gmail.com']) }}
{{--                            <input type="email" name="email" class="form-control" id="inputEmail2" placeholder="example@gmal.com">--}}
                            @error('email')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPhone2">Phone Number</label>
                            {{ Form::text('phone',null,['class'=>'form-control','placeholder'=>'0123456789']) }}
{{--                            <input type="number" name="phone" class="form-control" id="inputPhone2" placeholder="0123456789">--}}
                            @error('phone')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputAddress">Addess</label>
                            {{ Form::text('address',null,['class'=>'form-control','placeholder'=>'Address']) }}
{{--                            <input type="text" name="address" class="form-control" id="inputAddress">--}}
                            @error('address')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="exampleInputFile">Avatar</label> </br>
                            {{ Form::file('avatar',null,['class'=>'form-control-file','id'=>'exampleInputFile','aria-describedby'=>'fileHelp']) }}
{{--                            <input type="file" name="avatar" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">--}}
                            <small id="fileHelp" class="form-text text-muted">File phải có định dạng png hoặc jpg.</small>
                            @error('avatar')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputBirthday4">Course</label>
                            <select name="course_id"  id="inputState" class="form-control">
                                @foreach($courses as $cou)
                                    <option value="{{$cou->id}}">{{$cou->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPassword4">Password (Default)</label>
                            <input type="password" name="password" readonly value="123456" class="form-control" id="inputPassword">
                            @error('password')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

backend_project/resources/views/students/list.blade.php
@extends('layouts.index')
@section('content')
    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            {!! Session::get('success') !!}
        </div>
    @endif
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">{{__('messages.Student-list')}}</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">{{__('messages.Student-list')}}</li>
            </ol>
            <!--filter-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white">
                {!! Form::open(['method'=>'GET']) !!}
                <div class="navbar-collapse">
                    <a class="nav-link p-3 m-2 border text-info d-inline-block" href="{{ route('students.create') }}">
{{--                                <i class="fas fa-plus"></i>--}}
                        {!! __('messages.Student-create') !!}
                    </a>
                    <div class="list-group">
                        <div class="form-row text-secondary">
                            <b class="col-md-3">{{__('messages.Phone')}}:</b>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::checkbox('phone[]','viettel',$request->has('phone')?in_array('viettel', $request->phone):false,['id'=>'phone1','class'=>'filter-phone form-check-input']) !!}
                                {!! Form::label('phone1', 'Viettel') !!}
                            </div>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::checkbox('phone[]','vinaphone',$request->has('phone')?in_array('vinaphone', $request->phone):false,['id'=>'phone2','class'=>'filter-phone form-check-input']) !!}
                                {!! Form::label('phone2', 'Vinaphone') !!}
                            </div>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::checkbox('phone[]','mobifone',$request->has('phone')?in_array('mobifone', $request->phone):false,['id'=>'phone3','class'=>'filter-phone form-check-input']) !!}
                                {!! Form::label('phone3', 'Mobifone') !!}
                            </div>
                        </div>
                        <div class="form-row text-secondary">
                            <b class="col-md-3">{{__('messages.Age')}}:</b>
                            <div class="form-group col-md-3">
                                {!! Form::number('age_min',$request->age_min,['class'=>'form-control filter-age','placeholder' => 'min']) !!}
                                @error('age_min')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <p> to :</p>
                            <div class="form-group col-md-3">
                                {!! Form::number('age_max',$request->age_max,['class'=>'form-control filter-age','placeholder' => 'max']) !!}
                                @error('age_max')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row text-secondary">
                            <b class="col-md-3">{{__('messages.Score')}}:</b>
                            <div class="form-group col-md-3">
                                {!! Form::number('score_min',$request->score_min,['class'=>'form-control filter-score','placeholder' => 'min']) !!}
                                @error('score_min')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <p> to :</p>
                            <div class="form-group col-md-3">
                                {!! Form::number('score_max',$request->score_max,['class'=>'form-control filter-score','placeholder' => 'max']) !!}
                                @error('score_max')
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row text-secondary">
                            <b class="col-md-3">{{__('messages.Status')}}:</b>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::radio('status','Passed',$request->status == 'Passed',['id'=>'status1','class'=>'filter-status form-check-input']) !!}
                                {!! Form::label('status1', __('messages.Passed')) !!}
                            </div>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::radio('status','Studying',$request->status == 'Studying',['id'=>'status2','class'=>'filter-status form-check-input']) !!}
                                {!! Form::label('status2', __('messages.Studying')) !!}
                            </div>
                            <div class="form-check ml-3 form-check-inline">
                                {!! Form::radio('status','Failed',$request->status == 'Failed',['id'=>'status3','class'=>'filter-status form-check-input']) !!}
                                {!! Form::label('status3', __('messages.Failed')) !!}
                            </div>
                        </div>
                    </div>
                    <div class="d-inline ml-4">
                        {!! Form::submit('Filter',['class'=>'btn btn-primary','name'=>'filter']) !!}
                    </div>
                </div>

                <div id="action">
                    <span>Tags:</span>
                    <div class="tags d-inline">
                        @if($request->has('phone'))
                            @foreach($request->phone as $tag)
                                <span class="text-primary tag-{{$tag}}"><i class="fas fa-tag"></i> {{$tag}}</span>
                            @endforeach
                        @endif
                        @if($request->score_min + $request->score_max > 0)
                            <span class="text-primary tag-score"><i class="fas fa-tag"></i> score</span>
                        @endif
                        @if($request->age_min + $request->age_max > 0)
                            <span class="text-primary tag-age"><i class="fas fa-tag"></i> age</span>
                        @endif
                        @if($request->has('status'))
                                <span class="text-primary tag-{{$request->status}}"><i class="fas fa-tag"></i> {{__('messages.'.$request->status)}}</span>
                        @endif
                    </div>
                    <div class="clear-filter d-inline-block p-2">
                        <span> | </span>
                        <a href="{{ route('students.index') }}" class="text-info">all</a>
                    </div>
                </div>
                {{ Form::close() }}
            </nav>
            <!--end filter-->
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    DataTable Students
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" width="100%" cellspacing="0">
                            <thead id="table" data-url="/students">
                            <tr>
                                <th>ID</th>
                                <th>{{__('messages.Name')}}</th>
                                <th>{{__('messages.Phone')}}</th>
                                <th>Email</th>
                                <th>{{__('messages.Course')}}</th>
                                <th>{{__('messages.Score')}}</th>
                                <th>{{__('messages.Avatar')}}</th>
                                <th>{{__('messages.Birthday')}}</th>
                                <th>{{__('messages.Status')}}</th>
                                <th>{{__('messages.Option')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($students as $index => $student)
                                <tr id="row-{{ $student->id }}">
                                    <td>{{$student->id}}</td>
                                    <td>{{ $student->name }}</td>
                                    <td>{{ $student->phone }}</td>
                                    <td>{{ $student->email }}</td>
                                    <td>{{ $student->course->name??'--Underfined--'}}</td>
                                    <td>{{ $student->avg_score}}</td>
                                    <td>
                                        <img src="{{ asset("/images/avatars/" . $student->avatar) }}" class="rounded mx-auto d-block" width="40" alt="avatar">
                                    </td>
                                    <td>{{ $student->birthday}}</td>
                                    <td class="text-center">
                                        @if($student->status == 0)
                                            <span class="text-info">{{__('messages.Studying')}}</span>
                                        @elseif($student->status == 1)
                                            <span class="text-success">{{__('messages.Passed')}}</span>
                                        @elseif($student->status == -1)
                                            <span class="text-secondary">{{__('messages.Failed')}}</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('students.edit',$student) }}" class="p-2 text-info">
                                            <i class="fas fa-user-edit"></i>
                                        </a>
                                        <a href="{{ route('students.subject',$student) }}" class="p-2 text-success">
                                            <i class="fas fa-book-reader"></i>
                                        </a>
                                        <a href="#" onclick="remove({{ $student->id }})" class="p-2 text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $students->appends($request->all())->links() }}
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection