backend_project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/roles', function () {
////    $permission = Permission::create(['name' => 'view']);
////    $user = \App\User::find(2);
////      $user->assignRole('student');
////    dd($users);
////    $role = Role::find(2);
////    $permission = Permission::find(2);
////    $role->givePermissionTo($permission);
//});

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/callback/{provider}', 'SocialController@callback');
Auth::routes();
Route::get('/logout','AuthController@logout')
    ->name('logout');
Route::get('lang/{lang}','LangController@changeLang')->name('language');



Route::middleware('auth')->group(function(){

    // Chỉ có role là admin mới có thể truy cập vào các route của group này
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/','DashboardController@dashboard')
            ->name('home');
        Route::get('/dashboard','DashboardController@dashboard')
            ->name('dash');
        Route::match(['get','post'],'/register','AuthController@register')
            ->name('register');
        //student
        Route::resource('students', 'StudentController');
        //Course
        Route::resource('courses', 'CourseController');
        //Subject
        Route::resource('subjects', 'SubjectController');
        //Result
        Route::resource('results','ResultController');
        //SendMail
        Route::resource('email','SendMailController');
        Route::get( '/students/{id}/subject', 'StudentController@subject')->where(['[0-9]+'])
            ->name('students.subject');
        Route::put( '/students', 'StudentController@index')
            ->name('students.filter');
        Route::get( '/account/faker', 'StudentController@dataFaker');

        Route::group(['prefix' => 'chat'],function () {
            Route::get('/admin','ChatController@admin')->name('chat.admin');
        });

    });


        Route::post('/chat/pusher','ChatController@pusher')->name('chat.pusher');
        Route::get('/chat','ChatController@index')->name('chat.index');

        Route::get('/students/{student}','StudentController@show')->name('students.show');
        Route::get('/subjects-result','ResultController@index')->name('results.index');
        Route::put('/subjects-update','ResultController@updateForStudent')
            ->name('results.updateForStudent');


});

backend_project/app/Http/Controllers/SendMailController.php
<?php
namespace App\Http\Controllers;

use App\Http\Requests\Mails\MailCreateRequest;
use App\Jobs\SendMail;
use App\Mail\Mailler;
use App\Repositories\Results\ResultRepository;
use App\Repositories\Students\StudentRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class SendMailController extends Controller
{
    protected $resultRepository;
    protected $studentRepository;
    public function __construct(StudentRepository $student)
    {
        $this->studentRepository = $student;
    }

    public function index()
    {
        return view('sendMail.index');
    }

    public function store(MailCreateRequest $request)
    {
        $this->studentRepository->sendMail($request);
        return redirect()->route('email.index');
    }
}

backend_project/resources/views/sendMail/content.blade.php
Hi, <b>{{$name}}</b>
<p>
    Chúc <b>{{$name}}</b> một ngày tốt lành!
</p>
<p>
    {{$content}}
</p>
<p>
    --Project Student--
</p>

backend_project/resources/views/sendMail/index.blade.php
@extends('layouts.index')
@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">{{__('messages.Mailler')}}</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('dash') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">{{__('messages.Mailler')}}</li>
        </ol>
        <!--filter-->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">Custom</button>
                    </li>
                </ul>
            </div>
        </nav>
        <hr/>
        {{ Form::open(['url' => route('email.store'), 'method' => 'POST', 'class' => 'form-horizontal form-label-left']) }}
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="jp_cp_right_side_wrapper">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            {{Form::text('email',null,['placeholder'=>'Email' , 'class'=>'form-control'])}}
                            @error('email')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            {{Form::text('name',null,['placeholder'=>'Name' , 'class'=>'form-control'])}}
                            @error('name')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            {{Form::text('title',null,['placeholder'=>'Title' , 'class'=>'form-control'])}}
                            @error('title')
                            <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col">
                        {{Form::textarea('content',null,['placeholder'=>'Content' , 'class'=>'form-control'])}}
                        @error('content')
                        <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                        @enderror
                    </div>
                </div>
                <div></div>
                <div class="form-group">
                    <div class="col-md-12 col-sm-6 col-xs-12 col-md-offset-3">
                        {{ Form::button(__('Send Mail'), ['type' => 'submit','class' => 'btn btn-success'] ) }}
                    </div>
                </div>
            </div>
        </div>
    {{ Form::close() }}

    <!--Modal-->
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content p-3">
                {{Form::open(['url'=>route('email.store'), 'method'=>'POST', 'class'=>'form'])}}
                    <div class="row ml-3">
                        <div class="p-2 form-group col-md-3">
                            {{Form::radio('action','all',true,['id'=>'allStudent', 'class'=>'form-check-input'])}}
                            <label for="allStudent">All Student</label>
                        </div>
                        <div class="p-2 form-group col-md-3">
                            {{Form::radio('action','score',false,['id'=>'scoreStudent', 'class'=>'form-check-input'])}}
                            <label for="scoreStudent">Score < 5</label>
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::text('title',null,['class'=>'form-control','placeholder'=>'Title'])}}
                    </div>
                    <div class="form-group">
                        {{Form::textarea('content',null,['placeholder'=>'Content' , 'class'=>'form-control'])}}
                    </div>
                    {{Form::submit('Send',['class'=>'btn btn-primary'])}}
                {{Form::close()}}
            </div>
        </div>
    </div>
@endsection